import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useAuth } from '../auth/useAuth';

export default function Home() {
  const { signIn, signOut, user } = useAuth();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        {!user && <button onClick={signIn}>Sign in with Twitter</button>}
        {!!user && `Signed-in with ${user.email}`}
        {!!user && <button onClick={signOut}>Sign out</button>}
      </main>
    </div>
  );
}
